=== 0xMYsteRy/misp-taxonomies/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-taxonomies",
  "id": "https://www.github.com/MISP/misp-taxonomies/schema.json",
  "defs": {
    "predicate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "string"
        },
        "colour": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "numerical_value": {
          "type": "number"
        },
        "expanded": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "entry": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "predicate": {
          "type": "string"
        },
        "entry": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "value": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "expanded": {
                "type": "string"
              },
              "numerical_value": {
                "type": "number"
              }
            },
            "required": [
              "value"
            ]
          }
        }
      }
    },
    "required": [
      "predicate"
    ]
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "namespace": {
      "type": "string"
    },
    "expanded": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "predicates": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "$ref": "#/defs/predicate"
      }
    },
    "values": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "$ref": "#/defs/entry"
      }
    },
    "refs": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "namespace",
    "description",
    "version",
    "predicates"
  ]
}

=== 0xMYsteRy/misp-taxonomies/iep2-policy-reference/machinetag.json
{
  "namespace": "iep2-policy-reference",
  "description": "Forum of Incident Response and Security Teams (FIRST) Information Exchange Policy (IEP) framework v2.0 policy reference",
  "version": 1,
  "predicates": [
    {
      "value": "id_ref",
      "expanded": "POLICY ID REFERENCE",
      "description": "Refers to a unique IEP Policy ID to identify a specific IEP policy at a remote location."
    },
    {
      "value": "url",
      "expanded": "URL",
      "description": "This is the remote URL specifying the IEP Policy File that contains the IEP Policy you wish to use."
    },
    {
      "value": "iep_version",
      "expanded": "IEP POLICY VERSION",
      "description": "States the version of the IEP framework that has been used. Must be set to 2.0."
    }
  ],
  "values": [
    {
      "predicate": "id_ref",
      "entry": [
        {
          "value": "$text",
          "expanded": "An id_ref value is required"
        }
      ]
    },
    {
      "predicate": "url",
      "entry": [
        {
          "value": "$text",
          "expanded": "A URL value is required"
        }
      ]
    },
    {
      "predicate": "iep_version",
      "entry": [
        {
          "value": "2.0",
          "expanded": "The IEP version value must be 2.0"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/cycat/machinetag.json
{
  "namespace": "cycat",
  "expanded": " Universal Cybersecurity Catalogue",
  "description": "Taxonomy used by cycat (Universal Cybersecurity Catalogue) to categorize namespace available in their cybersecurity catalogue.",
  "version": 1,
  "refs": [
    "https://www.cycat.org/"
  ],
  "values": [
    {
      "predicate": "type",
      "entry": [
        {
          "value": "tool",
          "expanded": "Tool",
          "description": "Cybersecurity tool is an open source or proprietaty tools used in the cybersecurity scope."
        },
        {
          "value": "playbook",
          "expanded": "Playbook",
          "description": "Cybersecurity playbook such as a defined set of rules with one or more actions triggered by different events to response, orchestrate or automate cybersecurity related actions."
        },
        {
          "value": "taxonomy",
          "expanded": "Taxonomy",
          "description": "Cybersecurity taxonomy is a set of labels used to classify (in both terms - arrange in classes or/and designe to national classification) cybersecurity related information."
        },
        {
          "value": "ruleset",
          "expanded": "Ruleset",
          "description": "Cybersecurity ruleset are rules used for detection in the cybersecurity field. Ruleset can be different format for (N/L)IDS (such as Snort, Suricata, Zeek, Sigma, Yara format) or any other tool capable of parsing such ruleset."
        },
        {
          "value": "notebook",
          "expanded": "Notebook",
          "description": "Cybersecurity notebook is an interactive document to code, experiment, train or visualize cybersecurity related information. A notebook can be in a different format such as Jupyter, Apache Zeppelin, Google Colab."
        },
        {
          "value": "vulnerability",
          "expanded": "Vulnerability",
          "description": "Vulnerability is a known (public or non-public) information about a security vulnerability in a specific software, hardware or service."
        },
        {
          "value": "proof-of-concept",
          "expanded": "Proof-of-concept",
          "description": "Cybersecurity proof-of-concept is a validation code to a known vulnerability."
        },
        {
          "value": "fingerprint",
          "expanded": "Fingerprint",
          "description": "Cybersecurity fingerprint are fingerprint to uniquely identify specific pattern. Fingerprint can be in different formats such as ja3, ja3s, hassh, jarm, favicon-mmh3."
        }
      ]
    },
    {
      "predicate": "scope",
      "entry": [
        {
          "value": "defense",
          "expanded": "Defense"
        },
        {
          "value": "detection",
          "expanded": "Detection"
        },
        {
          "value": "exploitation",
          "expanded": "Exploitation"
        },
        {
          "value": "investigation",
          "expanded": "Investigation"
        },
        {
          "value": "training",
          "expanded": "Training"
        }
      ]
    }
  ],
  "predicates": [
    {
      "value": "type",
      "expanded": "Type",
      "description": "Type of entry in the catalogue."
    },
    {
      "value": "scope",
      "expanded": "Scope",
      "description": "Scope of usage for the entry in the catalogue."
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/euci/machinetag.json
{
  "namespace": "euci",
  "description": "EU classified information (EUCI) means any information or material designated by a EU security classification, the unauthorised disclosure of which could cause varying degrees of prejudice to the interests of the European Union or of one or more of the Member States.",
  "version": 2,
  "predicates": [
    {
      "value": "EU-TOP-SECRET",
      "expanded": "EU TOP SECRET",
      "description": "Information and material the unauthorised disclosure of which could cause exceptionally grave prejudice to the essential interests of the European Union or of one or more of the Member States."
    },
    {
      "value": "EU-SECRET",
      "expanded": "EU SECRET",
      "description": "Information and material the unauthorised disclosure of which could seriously harm the essential interests of the European Union or of one or more of the Member States."
    },
    {
      "value": "EU-CONFIDENTIAL",
      "expanded": "EU CONFIDENTIAL",
      "description": "Information and material the unauthorised disclosure of which could harm the essential interests of the European Union or of one or more of the Member States."
    },
    {
      "value": "EU-RESTRICTED",
      "expanded": "EU RESTRICTED",
      "description": "Information and material the unauthorised disclosure of which could be disadvantageous to the interests of the European Union or of one or more of the Member States."
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/analyst-assessment/machinetag.json
{
  "namespace": "analyst-assessment",
  "expanded": "Analyst (Self) Assessment",
  "refs": [
    "http://www.foo.be/docs/intelligence/Tversky_Kahneman_1974.pdf",
    "http://www.foo.be/docs/intelligence/PsychofIntelNew.pdf"
  ],
  "description": "A series of assessment predicates describing the analyst capabilities to perform analysis or making judgments under a certain level of uncertainty. These assessment can be assigned by the analyst him/herself or by another party evaluating the analyst.",
  "version": 1,
  "predicates": [
    {
      "value": "experience",
      "expanded": "Experience",
      "description": "The analyst experience expressed in years range in the field tagged. The year range is based on a standard 40-hour work week."
    },
    {
      "value": "alternative-points-of-view-process",
      "expanded": "Alternative points of view process",
      "description": "A list of procedures or practices which describe alternative points of view to validate or rate an analysis. The list describes techniques or methods which could reinforce the estimative language in a human analysis and/or challenge the assumptions to reduce the potential bias of the analysis introduced by the analyst(s)."
    }
  ],
  "values": [
    {
      "predicate": "experience",
      "entry": [
        {
          "numerical_value": 1,
          "value": "less-than-1-year",
          "expanded": "Less than 1 year"
        },
        {
          "numerical_value": 2,
          "value": "between-1-and-5-years",
          "expanded": "Between 1 and 5 years"
        },
        {
          "numerical_value": 3,
          "value": "between-5-and-10-years",
          "expanded": "Between 5 and 10 years"
        },
        {
          "numerical_value": 4,
          "value": "between-10-and-20-years",
          "expanded": "Between 10 and 20 years"
        },
        {
          "numerical_value": 5,
          "value": "more-than-20-years",
          "expanded": "More than 20 years"
        }
      ]
    },
    {
      "predicate": "alternative-points-of-view-process",
      "entry": [
        {
          "value": "analytic-debates-within-the-organisation",
          "expanded": "analytic debates within the organisation"
        },
        {
          "value": "devils-advocates-methodology",
          "expanded": "Devil's advocates methodlogy"
        },
        {
          "value": "competitive-analysis",
          "expanded": "competitive analysis"
        },
        {
          "value": "interdisciplinary-brainstorming",
          "expanded": "interdisciplinary brainstorming"
        },
        {
          "value": "intra-office-peer-review",
          "expanded": "intra-office peer review"
        },
        {
          "value": "outside-expertise-review",
          "expanded": "Outside expertise review"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/event_classification/machinetag.json
{
  "namespace": "rtir_event_classification",
  "description": "Classify an RT/IR event",
  "version": 1,
  "predicates": [
    {
      "value": "event-class",
      "expanded": "Event Classification"
    }
  ],
  "values": [
    {
      "predicate": "event-class",
      "entry": [
        {
          "value": "incident_reports",
          "expanded": "Incident Reports"
        },
        {
          "value": "incidents",
          "expanded": "Incidents"
        },
        {
          "value": "investigations",
          "expanded": "Investigations"
        },
        {
          "value": "countermeasures",
          "expanded": "Countermeasures"
        },
        {
          "value": "general",
          "expanded": "General"
        },
        {
          "value": "exercises",
          "expanded": "Exercises"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/adversary/machinetag.json
{
  "namespace": "adversary",
  "description": "An overview and description of the adversary infrastructure",
  "version": 3,
  "predicates": [
    {
      "value": "infrastructure-status",
      "expanded": "Infrastructure Status"
    },
    {
      "value": "infrastructure-type",
      "expanded": "Infrastructure Type"
    },
    {
      "value": "infrastructure-state",
      "expanded": "Infrastructure State"
    }
  ],
  "values": [
    {
      "predicate": "infrastructure-status",
      "entry": [
        {
          "value": "unknown",
          "expanded": "Infrastructure ownership and status is unknown"
        },
        {
          "value": "compromised",
          "expanded": "Infrastructure compromised by or in the benefit of the adversary"
        },
        {
          "value": "own-and-operated",
          "expanded": "Infrastructure own and operated by the adversary"
        }
      ]
    },
    {
     "predicate": "infrastructure-state",
     "entry": [
        {
          "value": "unknown",
          "expanded": "Infrastructure state is unknown or cannot be evaluated"
        },
        {
          "value": "active",
          "expanded": "Infrastructure state is active and actively used by the adversary"
        },
        {
          "value": "down",
          "expanded": "Infrastructure state is known to be down"
        }
     ]
    },
    {
      "predicate": "infrastructure-type",
      "entry": [
        {
          "value": "unknown",
          "expanded": "Infrastructure usage by the adversary is unknown"
        },
        {
          "value": "proxy",
          "expanded": "Infrastructure used as proxy between the target and the adversary"
        },
        {
          "value": "drop-zone",
          "expanded": "Infrastructure used by the adversary to store information related to his campaigns"
        },
        {
          "value": "exploit-distribution-point",
          "expanded": "Infrastructure used to distribute exploit towards target(s)"
        },
        {
          "value": "vpn",
          "expanded": "Infrastructure used by the adversary as Virtual Private Network to hide activities and reduce the traffic analysis surface"
        },
        {
          "value": "panel",
          "expanded": "Panel used by the adversary to control or maintain his infrastructure"
        },
        {
          "value": "tds",
          "expanded": "Traffic Distribution Systems including exploit delivery or/and web monetization channels"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/accessnow/machinetag.json
{
  "namespace": "accessnow",
  "description": "Access Now",
  "version": 1,
  "predicates": [
    {
      "value": "anti-corruption-transparency",
      "expanded": "Anti-Corruption and transparency",
      "description": "The organization campaigns, or takes other actions against corruption and transparency."
    },
    {
      "value": "anti-war-violence",
      "expanded": "Anti-War / Anti-Violence",
      "description": "The organization campaigns, or takes other actions against war"
    },
    {
      "value": "culture",
      "expanded": "Culture",
      "description": "The organization campaigns or acts to promote cultural events Humanitarian Aid/Need Issues: relates to improving life for individuals in the developing world (right to shelter, right to education, right to food, right to water)"
    },
    {
      "value": "economic-change",
      "expanded": "Economic Change",
      "description": "Issues of economic policy, wealth distribution, etc."
    },
    {
      "value": "education",
      "expanded": "Education",
      "description": "The organization is concerned with some form of education"
    },
    {
      "value": "election-monitoring",
      "expanded": "Election Monitoring",
      "description": "The organization is an election monitor, or involved in election monitoring"
    },
    {
      "value": "environment",
      "expanded": "Environment",
      "description": "The organization campaigns or acts to protect the environment"
    },
    {
      "value": "freedom-expression",
      "expanded": "Freedom of Expression",
      "description": "The organization is concerned with freedom of speech issues"
    },
    {
      "value": "freedom-tool-development",
      "expanded": "Freedom Tool Development",
      "description": "The organization develops tools for use in defending or extending digital rights"
    },
    {
      "value": "funding",
      "expanded": "Funding",
      "description": " The organization is a funder of organizations or projects working with at risk users"
    },
    {
      "value": "health",
      "expanded": "Health Issues",
      "description": "The organization prevents epidemic illness or acts on curing them"
    },
    {
      "value": "human-rights",
      "expanded": "Human Rights Issues",
      "description": "relating to the detection, recording, exposure, or challenging of abuses of human rights"
    },
    {
      "value": "internet-telecom",
      "expanded": "Internet and Telecoms",
      "description": "Issues of digital rights in electronic communications"
    },
    {
      "value": "lgbt-gender-sexuality",
      "expanded": "LGBT / Gender / Sexuality",
      "description": "Issues relating to the Lesbian, Gay, Bi, Transgender community"
    },
    {
      "value": "policy",
      "expanded": "Policy",
      "description": "The organization is a policy think-tank, or policy advocate"
    },
    {
      "value": "politics",
      "expanded": "Politics",
      "description": "The organization takes a strong political view or is a political entity"
    },
    {
      "value": "privacy",
      "expanded": "Privacy",
      "description": "Issues relating to the individual's reasonable right to privacy"
    },
    {
      "value": "rapid-response",
      "expanded": "Rapid Response",
      "description": "The organization provides rapid response type capability for civil society"
    },
    {
      "value": "refugees",
      "expanded": "Refugees",
      "description": "Issues relating to displaced people"
    },
    {
      "value": "security",
      "expanded": "Security",
      "description": "Issues relating to physical or information security"
    },
    {
      "value": "womens-right",
      "expanded": "Women's Rights",
      "description": "Issues pertaining to inequality between men and women, or issues of particular relevance to women"
    },
    {
      "value": "youth-rights",
      "expanded": "Youth Rights",
      "description": "Issues of particular relevance to youth"
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/extended-event/machinetag.json
{
  "namespace": "extended-event",
  "description": "Reasons why an event has been extended : ",
  "version": 1,
  "predicates": [
    {
      "value": "competitive-analysis",
      "expanded": "Competitive analysis"
    },
    {
      "value": "extended-analysis",
      "expanded": "Extended analysis"
    }
  ],
  "values": [
    {
      "predicate": "competitive-analysis",
      "entry": [
        {
          "value": "devil-advocate",
          "description": "Devil's advocate"
        },
        {
          "value": "absurd-reasoning",
          "expanded": "Absurd reasoning"
        },
	{
	"value": "role-playing",
	"expanded": "Role playing"
	}, 
	{
	"value": "crystal-ball",
	"expanded": "Crystal ball"
	}
      ]
    },
    {
      "predicate": "extended-analysis",
      "entry": [
        {
          "value": "automatic-expansion",
          "description": "Automatic expansion"
        },
        {
          "value": "aggressive-pivoting",
          "description": "Aggressive pivoting"
        }
      ]
    }
  ]
}
