=== 0xMYsteRy/misp-taxonomies/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-taxonomies",
  "id": "https://www.github.com/MISP/misp-taxonomies/schema.json",
  "defs": {
    "predicate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "string"
        },
        "colour": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "numerical_value": {
          "type": "number"
        },
        "expanded": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "entry": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "predicate": {
          "type": "string"
        },
        "entry": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "value": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "expanded": {
                "type": "string"
              },
              "numerical_value": {
                "type": "number"
              }
            },
            "required": [
              "value"
            ]
          }
        }
      }
    },
    "required": [
      "predicate"
    ]
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "namespace": {
      "type": "string"
    },
    "expanded": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "predicates": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "$ref": "#/defs/predicate"
      }
    },
    "values": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "$ref": "#/defs/entry"
      }
    },
    "refs": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "namespace",
    "description",
    "version",
    "predicates"
  ]
}

=== 0xMYsteRy/misp-taxonomies/information-security-data-source/machinetag.json
{
  "namespace": "information-security-data-source",
  "description": "Taxonomy to classify the information security data sources.",
  "refs": [
    "https://www.sciencedirect.com/science/article/pii/S0167404818304978"
  ],
  "version": 1,
  "predicates": [
    {
      "value": "originality",
      "expanded": "Originality",
      "description": "Originality and novelty of the provided information"
    },
    {
      "value": "timeliness-sharing-behavior",
      "expanded": "Timeliness sharing behavior",
      "description": "Timeliness of the provided information"
    },
    {
      "value": "type-of-information",
      "expanded": "Type of information",
      "description": "Type of provided information"
    },
    {
      "value": "integrability-format",
      "expanded": "Integrability format",
      "description": "Level of integrability format for the provided information"
    },
    {
      "value": "integrability-interface",
      "expanded": "Integrability interface",
      "description": "Level of integrability interface for the provided information"
    },
    {
      "value": "type-of-source",
      "expanded": "Type of source",
      "description": "Types of information security data source"
    },
    {
      "value": "trustworthiness-creditabilily",
      "expanded": "Trustworthiness creditability",
      "description": "Source of the creditability"
    },
    {
      "value": "trustworthiness-traceability",
      "expanded": "Trustworthiness traceability",
      "description": "Traceability of the provided information"
    },
    {
      "value": "trustworthiness-feedback-mechanism",
      "expanded": "Trustworthiness feedback mechanism",
      "description": "Feedback such as user ratings or comments regarding the usefulness of the provided information"
    }
  ],
  "values": [
    {
      "predicate": "type-of-information",
      "entry": [
        {
          "value": "vulnerability",
          "expanded": "Vulnerability",
          "description": ""
        },
        {
          "value": "threat",
          "expanded": "Threat",
          "description": ""
        },
        {
          "value": "countermeasure",
          "expanded": "Countermeasure",
          "description": ""
        },
        {
          "value": "attack",
          "expanded": "Attack",
          "description": ""
        },
        {
          "value": "risk",
          "expanded": "Risk",
          "description": ""
        },
        {
          "value": "asset",
          "expanded": "Asset",
          "description": ""
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/osint/machinetag.json
{
  "predicates": [
    {
      "expanded": "Source Type",
      "value": "source-type"
    },
    {
      "expanded": "Lifetime of the information as Open Source Intelligence",
      "value": "lifetime"
    }
  ],
  "version": 1,
  "description": "Open Source Intelligence - Classification (MISP taxonomies)",
  "namespace": "osint",
  "values": [
    {
      "predicate": "source-type",
      "entry": [
        {
          "value": "blog-post",
          "expanded": "Blog post"
        },
        {
          "value": "technical-report",
          "expanded": "Technical or analysis report"
        },
        {
          "value": "news-report",
          "expanded": "News report"
        },
        {
          "value": "pastie-website",
          "expanded": "Pastie-like website"
        },
        {
          "value": "electronic-forum",
          "expanded": "Electronic forum"
        },
        {
          "value": "mailing-list",
          "expanded": "Mailing-list"
        }
      ]
    },
    {
      "entry": [
        {
          "description": "Information available publicly on long-term",
          "expanded": "Perpetual",
          "value": "perpetual"
        },
        {
          "description": "Information available publicly on short-term",
          "expanded": "Ephemeral",
          "value": "ephemeral"
        }
      ],
      "predicate": "lifetime"
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/ics/machinetag.json
{
  "predicates": [
    {
      "expanded": "OT Components Category",
      "value": "ot-components-category"
    },
    {
      "expanded": "OT Operating Systems",
      "value": "ot-operating-systems"
    }
  ],
  "values": [
    {
      "predicate": "ot-operating-systems",
      "entry": [
        {
          "value": "rtos",
          "expanded": "RTOS",
          "description": "Please see the URL reference, there are a lot of it to be listed in here.  These OS are also referred as Firmware. https://en.wikipedia.org/wiki/Comparison_of_real-time_operating_systems"
        },
        {
          "value": "linux-embedded-base-os",
          "expanded": "Linux Embedded Base OS",
          "description": "Yocto\\nBuildroot\\nOpenWRT\\nB & R Linux\\n Scientific Linux\\nRaspbian\\nAndroid"
        },
        {
          "value": "bsd",
          "expanded": "BSD",
          "description": "NetBSD (NetBSD Embedded Systems)\\nFreeBSD (Modified. i.e.: Orbis OS)"
        },
        {
          "value": "microsoft",
          "expanded": "Microsoft",
          "description": "Windows 10 IoT Enterprise\\n Windows Embedded 8.1 Industry Professional\\n Windows 7 Professional/Ultimate\\n Windows Embedded Standard 7\\n Windows Embedded Standard 2009\\n Windows CE 6.0\\n"
        }
      ]
    },
    {
      "predicate": "ot-components-category",
      "entry": [
        {
          "value": "programmable-logic-controller",
          "expanded": "Programmable Logic Controller (PLC)",
          "description": "1. Computing device with user-programmable memory to storing instructions to operate a physical process.\\n\\n 2.Various PLC types for different processses"
        },
        {
          "value": "remote-terminal-unit",
          "expanded": "Remote Terminal Unit (RTU)",
          "description": "1. Data aquisitionand control unit designedto support field sites and remote stations.\\n\\n2. Wired and wireless communication capabilities.\\n\\n3. No stored program logic."
        },
        {
          "value": "human-machine-interface",
          "expanded": "Human-Machine Interface (HMI)",
          "description": "1. Hardware/software that operators used to interact with control system.\\n\\n2. From physical control panels to a complete computer systems"
        },
        {
          "value": "sensors",
          "expanded": "Sensors",
          "description": "Pressure, Temperature, Flow, Voltage, Optical, Proximity"
        },
        {
          "value": "actuators",
          "expanded": "Actuators",
          "description": "Variable Frequency Drive, Servo Drive, Valve, Circuit Breaker"
        },
        {
          "value": "communications",
          "expanded": "Communications",
          "description": "Modems, Routers, Serial - Ethernet Converters, Swtiches"
        },
        {
          "value": "supervisory-level-devices",
          "expanded": "Supervisory Level Devices",
          "description": "1. Control Server (Supervisory systems that hosts control software to manage lower level control devices like PLC).\\n\\n2. Data Historian (Centralized database for information about process, control activity and status record).\\n\\n3. Engineering workstations (Creating and revising control systems anbd programs, incl. project files)."
        }
      ]
    }
  ],
  "refs": [
    "https://www.first.org/global/sigs/cti/"
  ],
  "version": 1,
  "description": "FIRST.ORG CTI SIG - MISP Proposal for ICS/OT Threat Attribution (IOC) Project",
  "expanded": "Industrial Control System (ICS)",
  "namespace": "ics"
}

=== 0xMYsteRy/misp-taxonomies/phishing/machinetag.json
{
  "namespace": "phishing",
  "description": "Taxonomy to classify phishing attacks including techniques, collection mechanisms and analysis status.",
  "version": 2,
  "predicates": [
    {
      "value": "techniques",
      "expanded": "Techniques",
      "description": "Phishing techniques used."
    },
    {
      "value": "distribution",
      "expanded": "Distribution",
      "description": "How the phishing is distributed."
    },
    {
      "value": "report-type",
      "expanded": "Report type",
      "description": "How the phishing information was reported."
    },
    {
      "value": "report-origin",
      "expanded": "Report origin",
      "description": "Origin or source of the phishing information such as tools or services."
    },
    {
      "value": "action",
      "expanded": "Action",
      "description": "Action(s) taken related to the phishing tagged with this taxonomy."
    },
    {
      "value": "state",
      "expanded": "State",
      "description": "State of the phishing."
    },
    {
      "value": "psychological-acceptability",
      "expanded": "Psychological acceptability",
      "description": "Quality of the phishing by its level of acceptance by the target."
    }
  ],
  "values": [
    {
      "predicate": "techniques",
      "entry": [
        {
          "value": "fake-website",
          "expanded": "Social engineering fake website",
          "description": "Adversary controls a fake website to phish for credentials or information."
        },
        {
          "value": "email-spoofing",
          "expanded": "Social engineering email spoofing",
          "description": "Adversary sends email with domains related to target. Adversary controls the domains used."
        },
        {
          "value": "clone-phishing",
          "expanded": "Clone phishing",
          "description": "Adversary clones an email to target potential victims with duplicated content."
        },
        {
          "value": "voice-phishing",
          "expanded": "Voice phishing",
          "description": "Adversary use voice-based techniques to trick a potential victim to give credentials or sensitive information. This is also named as vishing."
        },
        {
          "value": "search-engines-abuse",
          "expanded": "Social engineering search engines abuse",
          "description": "Adversary controls the search engine result to get an advantage"
        },
        {
          "value": "sms-phishing",
          "expanded": "SMS phishing",
          "description": "Adversary sends an SMS to a potential victims to gather sensitive information or use another phishing techniques at a later stage."
        }
      ]
    },
    {
      "predicate": "distribution",
      "entry": [
        {
          "value": "spear-phishing",
          "expanded": "Spear phishing",
          "description": "Adversary attempts targeted phishing to a user or a specific group of users based on knowledge known by the adversary."
        },
        {
          "value": "bulk-phishing",
          "expanded": "Bulk phishing",
          "description": "Adversary attempts to target a large group of potential targets without specific knowledge of the victims."
        }
      ]
    },
    {
      "predicate": "report-type",
      "entry": [
        {
          "value": "manual-reporting",
          "expanded": "Manual reporting",
          "description": "Phishing reported by a human (e.g. tickets, manual reporting)."
        },
        {
          "value": "automatic-reporting",
          "expanded": "Automatic reporting",
          "description": "Phishing collected by automatic reporting (e.g. phishing report tool, API)."
        }
      ]
    },
    {
      "predicate": "report-origin",
      "entry": [
        {
          "value": "url-abuse",
          "expanded": "url-abuse",
          "description": "CIRCL url-abuse service."
        },
        {
          "value": "lookyloo",
          "expanded": "lookyloo",
          "description": "CIRCL lookyloo service."
        },
        {
          "value": "phishtank",
          "expanded": "Phishtank",
          "description": "Phishtank service."
        },
        {
          "value": "spambee",
          "expanded": "Spambee",
          "description": "C-3 Spambee service."
        }
      ]
    },
    {
      "predicate": "action",
      "entry": [
        {
          "value": "take-down",
          "expanded": "Take down",
          "description": "Take down notification sent to the operator where the phishing infrastructure is hosted."
        },
        {
          "value": "pending-law-enforcement-request",
          "expanded": "Pending law enforcement request",
          "description": "Law enforcement requests are ongoing on the phishing infrastructure."
        },
        {
          "value": "pending-dispute-resolution",
          "expanded": "Pending dispute resolution",
          "description": "Dispute resolution sent to competent authorities (e.g. domain authority, trademark dispute)."
        }
      ]
    },
    {
      "predicate": "state",
      "entry": [
        {
          "value": "unknown",
          "expanded": "Phishing state is unknown or cannot be evaluated",
          "numerical_value": 50
        },
        {
          "value": "active",
          "expanded": "Phishing state is active and actively used by the adversary",
          "numerical_value": 100
        },
        {
          "value": "down",
          "expanded": "Phishing state is known to be down",
          "numerical_value": 0
        }
      ]
    },
    {
      "predicate": "psychological-acceptability",
      "entry": [
        {
          "value": "unknown",
          "expanded": "Phishing acceptance rate is unknown."
        },
        {
          "value": "low",
          "expanded": "Phishing acceptance rate is low.",
          "numerical_value": 25
        },
        {
          "value": "medium",
          "expanded": "Phishing acceptance rate is medium.",
          "numerical_value": 50
        },
        {
          "value": "high",
          "expanded": "Phishing acceptance rate is high.",
          "numerical_value": 75
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/iep/machinetag.json
{
  "namespace": "iep",
  "description": "Forum of Incident Response and Security Teams (FIRST) Information Exchange Policy (IEP) framework",
  "version": 1,
  "predicates": [
    {
      "value": "id",
      "expanded": "POLICY ID",
      "description": "Provides a unique ID to identify a specific IEP implementation."
    },
    {
      "value": "version",
      "expanded": "POLICY VERSION",
      "description": "States the version of the IEP framework that has been used."
    },
    {
      "value": "name",
      "expanded": "POLICY NAME",
      "description": "This statement can be used to provide a name for an IEP implementation."
    },
    {
      "value": "start-date",
      "expanded": "POLICY START DATE",
      "description": "States the UTC date that the IEP is effective from."
    },
    {
      "value": "end-date",
      "expanded": "POLICY END DATE",
      "description": "States the UTC4 date that the IEP is effective until."
    },
    {
      "value": "reference",
      "expanded": "POLICY REFERENCE",
      "description": "This statement can be used to provide a URL reference to the specific IEP implementation."
    },
    {
      "value": "research",
      "expanded": "RESEARCH",
      "description": "Recipients could be permitted use of information received in research."
    },
    {
      "value": "commercial-use",
      "expanded": "COMMERCIAL USE",
      "description": "States whether Recipients are permitted to use information received in commercial products or services."
    },
    {
      "value": "terms-of-use",
      "expanded": "TERMS OF USE",
      "description": "This statement can be used to convey a description or reference to any applicable licenses, agreements, or conditions between the producer and receiver."
    },
    {
      "value": "encrypt-in-transit",
      "expanded": "ENCRYPT IN TRANSIT",
      "description": "States whether the received information has to be encrypted when it is retransmitted by the recipient."
    },
    {
      "value": "encrypt-at-rest",
      "expanded": "ENCRYPT AT REST",
      "description": "States whether the received information has to be encrypted by the Recipient when it is stored at rest."
    },
    {
      "value": "permitted-actions",
      "expanded": "PERMITTED ACTIONS",
      "description": "States the permitted actions that Recipients can take upon information received."
    },
    {
      "value": "victim-notifications",
      "expanded": "VICTIM NOTIFICATIONS",
      "description": "Recipients are permitted notify affected third parties of a potential compromise or threat."
    },
    {
      "value": "traffic-light-protocol",
      "expanded": "TRAFFIC LIGHT PROTOCOL",
      "description": "Recipients are permitted to redistribute the information received within the redistribution scope as defined by the enumerations."
    },
    {
      "value": "transitive-trust-required",
      "expanded": "TRANSITIVE TRUST REQUIRED",
      "description": "Policy Description Recipients are permitted to redistribute the information received only with third parties the Recipient can ensure will protect the information to the same extent as the Provider requires of the Recipient."
    },
    {
      "value": "provider-attribution",
      "expanded": "PROVIDER ATTRIBUTION",
      "description": "Recipients could be required to attribute or anonymize the Provider when redistributing the information received."
    },
    {
      "value": "obfuscate-victims",
      "expanded": "OBFUSCATE VICTIMS",
      "description": "Recipients could be required to obfuscate or anonymize information that could be used to identify the victims before redistributing the information received."
    }
  ],
  "values": [
    {
      "predicate": "research",
      "entry": [
        {
          "value": "MAY",
          "expanded": "Recipients MAY use this information for Research."
        },
        {
          "value": "MUST NOT",
          "expanded": "Recipients MUST NOT use this information for Research."
        }
      ]
    },
    {
      "predicate": "commercial-use",
      "entry": [
        {
          "value": "MAY",
          "expanded": "Recipients MAY use this information in commercial products or services."
        },
        {
          "value": "MUST NOT",
          "expanded": "Recipients MUST NOT use this information in commercial products or services."
        }
      ]
    },
    {
      "predicate": "terms-of-use",
      "entry": [
        {
          "value": "$text"
        }
      ]
    },
    {
      "predicate": "encrypt-in-transit",
      "entry": [
        {
          "value": "MUST",
          "expanded": "Recipients MUST encrypt the information received when it is retransmitted or redistributed."
        },
        {
          "value": "MAY",
          "expanded": "Recipients MAY encrypt the information received when it is retransmitted or redistributed."
        }
      ]
    },
    {
      "predicate": "encrypt-at-rest",
      "entry": [
        {
          "value": "MUST",
          "expanded": "Recipients MUST encrypt the information received when it is stored at rest."
        },
        {
          "value": "MAY",
          "expanded": "Recipients MAY encrypt the information received when it is stored at rest."
        }
      ]
    },
    {
      "predicate": "permitted-actions",
      "entry": [
        {
          "value": "NONE",
          "expanded": "Recipients MUST contact the Providers before acting upon the information received."
        },
        {
          "value": "CONTACT FOR INSTRUCTION",
          "expanded": "Recipients MUST contact the Providers before acting upon the information received."
        },
        {
          "value": "INTERNALLY VISIBLE ACTIONS",
          "expanded": "Recipients MAY conduct actions on the information received that are only visible on the Recipients internal networks and systems, and MUST NOT conduct actions that are visible outside of the Recipients networks and systems, or visible to third parties."
        },
        {
          "value": "EXTERNALLY VISIBLE INDIRECT ACTIONS",
          "expanded": "Recipients MAY conduct indirect, or passive, actions on the information received that are externally visible and MUST NOT conduct direct, or active, actions."
        },
        {
          "value": "EXTERNALLY VISIBLE DIRECT ACTIONS",
          "expanded": "Recipients MAY conduct direct, or active, actions on the information received that are externally visible."
        }
      ]
    },
    {
      "predicate": "victim-notifications",
      "entry": [
        {
          "value": "MAY",
          "expanded": "Recipients MAY conduct active actions that are externally visible, on the information received."
        },
        {
          "value": "MUST NOT",
          "expanded": "Recipients MUST NOT conduct active actions that are externally visible, on the information received."
        }
      ]
    },
    {
      "predicate": "traffic-light-protocol",
      "entry": [
        {
          "value": "RED",
          "expanded": "Personal for identified recipients only."
        },
        {
          "value": "AMBER",
          "expanded": "Limited sharing on the basis of need-to-know."
        },
        {
          "value": "GREEN",
          "expanded": "Community wide sharing."
        },
        {
          "value": "WHITE",
          "expanded": "Unlimited sharing."
        }
      ]
    },
    {
      "predicate": "transitive-trust-required",
      "entry": [
        {
          "value": "MAY",
          "expanded": "Recipients MAY redistribute the information with third parties the Recipient does not have a formal agreement with."
        },
        {
          "value": "MUST",
          "expanded": "Recipients MUST only redistribute information with third parties that will protect the information to the same extent the Provider requires of the Recipient."
        }
      ]
    },
    {
      "predicate": "provider-attribution",
      "entry": [
        {
          "value": "MAY",
          "expanded": "Recipients MAY attribute the Provider when redistributing the information received."
        },
        {
          "value": "MUST",
          "expanded": "Recipients MUST attribute the Provider when redistributing the information received."
        },
        {
          "value": "MUST NOT",
          "expanded": "Recipients MUST NOT attribute the Provider when redistributing the information received."
        }
      ]
    },
    {
      "predicate": "obfuscate-victims",
      "entry": [
        {
          "value": "MAY",
          "expanded": "Recipients MAY obfuscate information about the specific victims."
        },
        {
          "value": "MUST",
          "expanded": "Recipients MUST obfuscate information about the specific victims."
        },
        {
          "value": "MUST NOT",
          "expanded": "Recipients MUST NOT obfuscate information about the specific victims."
        }
      ]
    },
    {
      "predicate": "start-date",
      "entry": [
        {
          "value": "$text"
        }
      ]
    },
    {
      "predicate": "end-date",
      "entry": [
        {
          "value": "$text"
        }
      ]
    },
    {
      "predicate": "reference",
      "entry": [
        {
          "value": "$text"
        }
      ]
    },
    {
      "predicate": "name",
      "entry": [
        {
          "value": "$text"
        }
      ]
    },
    {
      "predicate": "version",
      "entry": [
        {
          "value": "$text"
        }
      ]
    },
    {
      "predicate": "id",
      "entry": [
        {
          "value": "$text"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/kill-chain/machinetag.json
{
  "namespace": "kill-chain",
  "expanded": "Cyber Kill Chain",
  "description": "The Cyber Kill Chain, a phase-based model developed by Lockheed Martin, aims to help categorise and identify the stage of an attack.",
  "version": 1,
  "predicates": [
    {
      "value": "Reconnaissance",
      "expanded": "This is the first and most important opportunity for defenders to block the operation. A key measure of effectiveness is the fraction of intrusion attempts that are blocked at delivery stage."
    },
    {
      "value": "Weaponisation",
      "expanded": "This is the first and most important opportunity for defenders to block the operation. A key measure of effectiveness is the fraction of intrusion attempts that are blocked at delivery stage."
    },
    {
      "value": "Delivery",
      "expanded": "This is the first and most important opportunity for defenders to block the operation. A key measure of effectiveness is the fraction of intrusion attempts that are blocked at delivery stage. "
    },
    {
      "value": "Exploitation",
      "expanded": "Here traditional hardening measures add resiliency, but custom capabilities are necessary to stop zero-day exploits at this stage."
    },
    {
      "value": "Installation",
      "expanded": "Here traditional hardening measures add resiliency, but custom capabilities are necessary to stop zero-day exploits at this stage."
    },
    {
      "value": "Command and Control",
      "expanded": "The defender’s last best chance to block the operation: by blocking the C2 channel. If adversaries can’t issue commands, defenders can prevent impact."
    },
    {
      "value": "Actions on Objectives",
      "expanded": "The defender’s last best chance to block the operation: by blocking the C2 channel. If adversaries can’t issue commands, defenders can prevent impact."
    }
  ]
}
