=== 0xMYsteRy/misp-taxonomies/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Validator for misp-taxonomies",
  "id": "https://www.github.com/MISP/misp-taxonomies/schema.json",
  "defs": {
    "predicate": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "value": {
          "type": "string"
        },
        "colour": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "numerical_value": {
          "type": "number"
        },
        "expanded": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "entry": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "predicate": {
          "type": "string"
        },
        "entry": {
          "type": "array",
          "uniqueItems": true,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "value": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "expanded": {
                "type": "string"
              },
              "numerical_value": {
                "type": "number"
              }
            },
            "required": [
              "value"
            ]
          }
        }
      }
    },
    "required": [
      "predicate"
    ]
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "namespace": {
      "type": "string"
    },
    "expanded": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "version": {
      "type": "integer"
    },
    "predicates": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "$ref": "#/defs/predicate"
      }
    },
    "values": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "object",
        "$ref": "#/defs/entry"
      }
    },
    "refs": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "namespace",
    "description",
    "version",
    "predicates"
  ]
}

=== 0xMYsteRy/misp-taxonomies/honeypot_basic/machinetag.json
{
  "namespace": "honeypot_basic",
  "description": "Christian Seifert, Ian Welch, Peter Komisarczuk, ‘Taxonomy of Honeypots’, Technical Report CS-TR-06/12, VICTORIA UNIVERSITY OF WELLINGTON, School of Mathematical and Computing Sciences, June 2006, http://www.mcs.vuw.ac.nz/comp/Publications/archive/CS-TR-06/CS-TR-06-12.pdf",
  "version": 1,
  "predicates": [
    {
      "value": "interaction-level",
      "expanded": "Interaction Level",
      "description": "Describes whether the exposed functionality of a honeypot is limited in some way, which is usually the case for honeypots that simulate services."
    },
    {
      "value": "data-capture",
      "expanded": "Data Capture",
      "description": "Describes the type of data a honeypot is able to capture"
    },
    {
      "value": "interaction-level",
      "expanded": "Interaction Level",
      "description": "Describes whether the exposed functionality of a honeypot is limited in some way, which is usually the case for honeypots that simulate services."
    },
    {
      "value": "interaction-level",
      "expanded": "Interaction Level",
      "description": "Describes whether the exposed functionality of a honeypot is limited in some way, which is usually the case for honeypots that simulate services."
    },
    {
      "value": "interaction-level",
      "expanded": "Interaction Level",
      "description": "Describes whether the exposed functionality of a honeypot is limited in some way, which is usually the case for honeypots that simulate services."
    },
    {
      "value": "interaction-level",
      "expanded": "Interaction Level",
      "description": "Describes whether the exposed functionality of a honeypot is limited in some way, which is usually the case for honeypots that simulate services."
    }
  ],
  "values": [
    {
      "predicate": "interaction-level",
      "entry": [
        {
          "value": "high",
          "expanded": "High Interaction Level",
          "description": "Exposed functionality of the honeypot is not limited."
        },
        {
          "value": "low",
          "expanded": "low Interaction Level",
          "description": "Exposed functionality being limited. For example, a simulated SSH server of a honeypot is not able to authenticate against a valid login/password combination"
        }
      ]
    },
    {
      "predicate": "data-capture",
      "entry": [
        {
          "value": "events",
          "expanded": "Events",
          "description": "The honeypot collects data about something that has happened or took place, a change in state."
        },
        {
          "value": "attacks",
          "expanded": "Attacks",
          "description": "The honeypot collects malicious activity."
        },
        {
          "value": "intrusions",
          "expanded": "Intrusions",
          "description": "The honeypot collects malicious activity that leads to a security failure."
        },
        {
          "value": "none",
          "expanded": "None",
          "description": "The honeypot does not collect events, attacks, or intrusions."
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/iot/machinetag.json
{
  "namespace": "iot",
  "description": "Internet of Things taxonomy, based on IOT UK report https://iotuk.org.uk/wp-content/uploads/2017/01/IOT-Taxonomy-Report.pdf",
  "version": 1,
  "expanded": "Internet of Things",
  "predicates": [
    {
      "value": "TCom",
      "expanded": "Technical complexity",
      "description":"IoT projects vary tremendously in terms of their technical sophistication . Digital Catapult has developed a scale based on technology complexity (TCom) that enables us to understand the state of IoT in the UK, and to assess what is currently being researched, trialled or deployed in real-life implementations ."
    },
    {
      "value": "SSL",
      "expanded": "System Security Level",
      "description": "A second characteristic of an IoT system concerns the inherent level of safety, privacy and security of that system . At one end of the spectrum, an IoT system may not gather data that is sensitive either in terms of safety or privacy, while at the other it may collect data about identifiable individuals or groups of individuals, involve financial transactions, or access to system data or have the ability to control objects that could compromise health, safety or security."
    },
    {
      "value": "DSL",
      "expanded": "Data Sharing Level",
      "description": "A third characteristic of IoT systems concerns the degree of sharing of sensitive data between the object and the system, and subsequently between the system and the system operator(s) or participants, and third parties .Systems do not always need to share data, so IoT product, platform, service and system designers must be clear about when data is shared, what is shared and why."
    }
  ]

}

=== 0xMYsteRy/misp-taxonomies/dark-web/machinetag.json
{
  "namespace": "dark-web",
  "expanded": "Dark Web",
  "description": "Criminal motivation on the dark web: A categorisation model for law enforcement. ref: Janis Dalins, Campbell Wilson, Mark Carman. Taxonomy updated by MISP Project",
  "version": 1,
  "predicates": [
    {
      "value": "topic",
      "description": "Topic associated with the materials tagged",
      "expanded": "Topic"
    },
    {
      "value": "motivation",
      "description": "Motivation with the materials tagged",
      "expanded": "Motivation"
    }
  ],
  "values": [
    {
      "predicate": "topic",
      "entry": [
        {
          "value": "drugs-narcotics",
          "expanded": "Drugs/Narcotics",
          "description": "Illegal drugs/chemical compounds for consumption/ingestion - either via blanket unlawfulness (e.g. proscribed drugs) or via unlawful access (e.g. prescription-only/restricted medications sold without lawful accessibility)."
        },
        {
          "value": "extremism",
          "expanded": "Extremism",
          "description": "Illegal or ‘of concern’ levels of extremist ideology. Note this does not provide blanket coverage of fundamentalist ideologies and dogma - only those associated with illegal acts. Socialist/anarchist/religious materials (for example) will not be included unless inclusive or indicative of associated illegal conduct, such as hate crimes."
        },
        {
          "value": "finance",
          "expanded": "Finance",
          "description": "Any monetary/currency/exchangeable materials. Includes carding, Bitcoin, Litecoin etc."
        },
        {
          "value": "hacking",
          "expanded": "Hacking",
          "description": "Materials relating to the illegal access to or alteration of data and/or electronic services."
        },
        {
          "value": "identification-credentials",
          "expanded": "Identification/Credentials",
          "description": "Materials used for providing/establishing identification with third parties. Examples include passports, driver licenses and login credentials."
        },
        {
          "value": "intellectual-property-copyright-materials",
          "expanded": "Intellectual Property/Copyright Materials",
          "description": "Otherwise lawful materials stored, transferred or made available without consent of their legal rights holders."
        },
        {
          "value": "pornography-adult",
          "expanded": "Pornography - Adult",
          "description": "Lawful, ethical pornography (i.e. involving only consenting adults)."
        },
        {
          "value": "pornography-child-exploitation",
          "expanded": "Pornography - Child (Child Exploitation)",
          "description": "Child abuse materials (aka child pornography), including 'fantasy' fiction materials, CGI. Also includes the provision/offering of child abuse materials and/or activities"
        },
        {
          "value": "pornography-illicit-or-illegal",
          "expanded": "Pornography - Illicit or Illegal",
          "description": "Illegal pornography NOT including children/child abuse. Includes bestiality, stolen/revenge porn, hidden cameras etc."
        },
        {
          "value": "search-engine-index",
          "expanded": "Search Engine/Index",
          "description": "Site providing links/references to other sites/services. Referred to as a ‘nexus’ by (Moore and Rid, 2016)"
        },
        {
          "value": "unclear",
          "expanded": "Unclear",
          "description": "Unable to completely establish topic of material."
        },
        {
          "value": "violence",
          "expanded": "Violence",
          "description": "Materials relating to violence against persons or property."
        },
        {
          "value": "weapons",
          "expanded": "Weapons",
          "description": "Materials specifically associated with materials and/or items for use in violent acts against persons or property. Examples include firearms and bomb-making ingredients."
        },
        {
          "value": "other-not-illegal",
          "expanded": "Other not illegal",
          "description": "Material not of interest to law enforcement - e.g. personal sites, Facebook mirrors."
        }
      ]
    },
    {
      "predicate": "motivation",
      "entry": [
        {
          "value": "education-training",
          "expanded": "Education & Training",
          "description": "Materials providing instruction - e.g. ‘how to’ guides"
        },
        {
          "value": "file-sharing",
          "expanded": "File Sharing",
          "description": "General file sharing, typically (but not limited to) movie/image sharing"
        },
        {
          "value": "forum",
          "expanded": "Forum",
          "description": "Sites specifically designed for multiple users to communicate as peers"
        },
        {
          "value": "general",
          "expanded": "General",
          "description": "Materials not covered by the other motivations. Typically, materials of a nature not of interest to law enforcement.  For example, personal biography sites."
        },
        {
          "value": "information-sharing-reportage",
          "expanded": "Information Sharing/Reportage",
          "description": "Journalism/reporting on topics. Can include biased coverage, but obvious propaganda materials are covered by Recruitment/Advocacy."
        },
        {
          "value": "marketplace-for-sale",
          "expanded": "Marketplace/For Sale",
          "description": "Services/goods for sale, regardless of means of payment."
        },
        {
          "value": "recruitment-advocacy",
          "expanded": "Recruitment/Advocacy",
          "description": "Propaganda"
        },
        {
          "value": "system-placeholder",
          "expanded": "System/Placeholder",
          "description": "Automatically generated content, not designed for any identifiable purpose other than diagnostics - e.g. “It Works” message provided by default by Apache2"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/nis-impact/machinetag.json
{
  "namespace": "nis-impact",
  "description": "This taxonomy is used to classify the impact of the incident, i.e. the impact it has on services, in which sector(s) of the economy and society.",
  "version": 1,
  "predicates": [
    {
      "value": "sectors-impacted",
      "expanded": "Sectors impacted",
      "description": "The impact on services, in the real world, indicating the sectors of the society and economy, where there is an impact on the services."
    },
    {
      "value": "severity",
      "expanded": "Severity of the impact",
      "description": "The severity of the impact, nationally, in the real world, for society and/or the economy, i.e. the level of disruption for the country or a large region of the country, the level of risks for health and/or safety, the level of physical damages and/or financial costs."
    },
    {
      "value": "outlook",
      "expanded": "Outlook",
      "description": "The outlook for the incident, the prognosis, for the coming hours, considering the impact in the real world, the impact on services, for the society and/or the economy"
    }
  ],
  "values": [
    {
      "predicate": "sectors-impacted",
      "entry": [
        {
          "value": "energy",
          "expanded": "Energy",
          "description": "The impact is in the Energy sector and its subsectors such as electricity, oil, or gas, for example, impacting electricity suppliers, power plants, distribution system operators, transmission system operators, oil transmission, natural gas distribution, etc."
        },
        {
          "value": "transport",
          "expanded": "Transport",
          "description": "The impact is in the transport sector and subsectors such as air, rail, water, road, for example, impacting air traffic control systems, railway companies, maritime port authorities, road traffic management systems, etc."
        },
        {
          "value": "banking",
          "expanded": "Banking",
          "description": "The impact is in the Banking sector, for example impacting banks, online banking, credit services, payment services, etc."
        },
        {
          "value": "financial",
          "expanded": "Financial",
          "description": "The impact is in the Financial market infrastructure sector, for example, impacting traders, trading platforms, clearing services, etc."
        },
        {
          "value": "health",
          "expanded": "Health",
          "description": "The impact is in the Health sector, for example, impacting hospitals, medical devices, medicine supply, pharmacies, etc."
        },
        {
          "value": "drinking-water",
          "expanded": "Drinking water",
          "description": "The impact is in the Drinking water supply and distribution sector, for example impacting drinking water supply, drinking water distribution systems, etc."
        },
        {
          "value": "digital-infrastructure",
          "expanded": "Digital infrastructure",
          "description": "The impact is in the Digital infrastructure sector, for example impacting internet exchange points, domain name systems, top level domain registries, etc."
        },
        {
          "value": "communications",
          "expanded": "Communications",
          "description": "The impact is in the Electronic communications sector, for example,impacting mobile network services, fixed telephone lines, satellite communications, etc."
        },
        {
          "value": "digital-services",
          "expanded": "Digital services",
          "description": "The impact is in the digital services sector, for example, impacting cloud services, online market places, online search engines, etc."
        },
        {
          "value": "trust-and-identification-services",
          "expanded": "Trust and identification services",
          "description": "The impact is in the electronic trust and identification services, for example, impacting certificate authorities, electronic identity systems, smartcards, etc."
        },
        {
          "value": "government",
          "expanded": "Government",
          "description": "The impact is in the government sector, for example, impacting the functioning of public administrations, elections, or emergency services"
        }
      ]
    },
    {
      "predicate": "severity",
      "entry": [
        {
          "value": "red",
          "expanded": "Red",
          "description": "Very large impact"
        },
        {
          "value": "yellow",
          "expanded": "Yellow",
          "description": "Large impact."
        },
        {
          "value": "green",
          "expanded": "Green",
          "description": "Minor impact."
        },
        {
          "value": "white",
          "expanded": "White",
          "description": "No impact."
        }
      ]
    },
    {
      "predicate": "outlook",
      "entry": [
        {
          "value": "improving",
          "expanded": "Improving",
          "description": "Severity of impact is expected to decrease in the next 6 hours."
        },
        {
          "value": "stable",
          "expanded": "Stable",
          "description": "Severity of impact is expected to remain the same in the 6 hours."
        },
        {
          "value": "worsening",
          "expanded": "Worsening",
          "description": "Severity of impact is expected to increase in the next 6 hours."
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/workflow/machinetag.json
{
  "namespace": "workflow",
  "expanded": "workflow to support analysis",
  "description": "Workflow support language is a common language to support intelligence analysts to perform their analysis on data and information. ",
  "version": 2,
  "predicates": [
    {
      "value": "todo",
      "expanded": "Todo",
      "description": "Todo are the actions to be performed by one or more analyst(s) to apply cognitive methods, evaluation(s), weightening information, to validate hypothesis or complete additional tasks to improve the overall information or data being tagged with a todo. "
    },
    {
      "value": "state",
      "expanded": "State",
      "description": "State are the different states of the information or data being tagged."
    }
  ],
  "values": [
    {
      "predicate": "todo",
      "entry": [
        {
          "value": "expansion",
          "expanded": "Expansion need to be applied to expand the information tagged"
        },
        {
          "value": "review",
          "expanded": "Additional review is required to reach a certain level of validation of the information tagged"
        },
        {
          "value": "review-before-publication",
          "expanded": "Review is required before publishing the information tagged"
        },
        {
          "value": "review-for-false-positive",
          "expanded": "Review the the information tagged to limit the number of false-positives and potentially remove any IDS/automation flag to avoid automation of the false-positives"
        },
        {
          "value": "review-the-source-credibility",
          "expanded": "Review the source credibility and add the corresponding marking like admiralty-scale on the origin"
        },
        {
          "value": "create-missing-misp-galaxy-cluster-values",
          "expanded": "Add potential MISP galaxy cluster values missing about the information tagged"
        },
        {
          "value": "create-missing-misp-galaxy-cluster",
          "expanded": "Create missing MISP galaxy cluster about the information tagged"
        },
        {
          "value": "add-context",
          "expanded": "Add contextual information about the information tagged"
        },
        {
          "value": "add-tagging",
          "expanded": "Add adequate tagging and classification about the information tagged"
        },
        {
          "value": "check-passive-dns-for-shared-hosting",
          "expanded": "Check Passive DNS (or similar techniques) to review if the information tagged is used within shared hosting"
        },
        {
          "value": "review-classification",
          "expanded": "Review the classification of the information tagged to ensure adequate marking of the information before publication"
        },
        {
          "value": "review-the-grammar",
          "expanded": "Review the grammar of the information tagged to improve the overall quality "
        }
      ]
    },
    {
      "predicate": "state",
      "entry": [
        {
          "value": "incomplete",
          "expanded": "Incomplete means that the information tagged is incomplete and has potential to be completed by other analysts, technical processes or the current analysts performing the analysis"
        },
        {
          "value": "complete",
          "expanded": "Complete means that the information tagged reach a state of completeness with the current capabilities of the analyst"
        }
      ]
    }
  ]
}

=== 0xMYsteRy/misp-taxonomies/mwdb/machinetag.json
{
  "namespace": "mwdb",
  "description": "Malware Database (mwdb) Taxonomy - Tags used across the platform",
  "version": 1,
  "predicates": [
    {
      "value": "location_type",
      "expanded": "Location Type",
      "description": "Type of malicious URL."
    },
    {
      "value": "family",
      "expanded": "Malware Family"
    }
  ],
  "values": [
    {
      "predicate": "location_type",
      "entry": [
        {
          "value": "cnc",
          "expanded": "CNC",
          "description": "C&C server, usually administrated by criminals. Malware connects to it (usually with a custom protocol) to get new commands and updates."
        },
        {
          "value": "download_url",
          "expanded": "Download URL",
          "description": "Download url. Used to download more malware samples. Sometimes just a hacked legitimate website."
        },
        {
          "value": "panel",
          "expanded": "Panel",
          "description": "Malware panel. HTTP service used by criminals to manage the botnet."
        },
        {
          "value": "peer",
          "expanded": "Peer",
          "description": "Peer. IP/port of infected machine of a legitimate computer user."
        },
        {
          "value": "other",
          "expanded": "Other",
          "description": "Other kind of URL found in the malware."
        }
      ]
    },
    {
      "predicate": "family",
      "entry": [
        {
          "value": "agenttesla"
        },
        {
          "value": "andromeda"
        },
        {
          "value": "anubis"
        },
        {
          "value": "avemaria"
        },
        {
          "value": "azorult"
        },
        {
          "value": "brushaloader"
        },
        {
          "value": "bublik"
        },
        {
          "value": "bunitu"
        },
        {
          "value": "cerber"
        },
        {
          "value": "chthonic"
        },
        {
          "value": "citadel"
        },
        {
          "value": "corebot"
        },
        {
          "value": "cryptomix"
        },
        {
          "value": "cryptoshield"
        },
        {
          "value": "cryptowall"
        },
        {
          "value": "danabot"
        },
        {
          "value": "danaloader"
        },
        {
          "value": "dridex"
        },
        {
          "value": "dridex-worker"
        },
        {
          "value": "dyre"
        },
        {
          "value": "emotet"
        },
        {
          "value": "emotet5_upnp"
        },
        {
          "value": "emotet_doc"
        },
        {
          "value": "emotet_spam"
        },
        {
          "value": "emotet_upnp"
        },
        {
          "value": "evil-pony"
        },
        {
          "value": "flokibot"
        },
        {
          "value": "formbook"
        },
        {
          "value": "gandcrab"
        },
        {
          "value": "get2"
        },
        {
          "value": "globeimposter"
        },
        {
          "value": "gluedropper"
        },
        {
          "value": "gootkit"
        },
        {
          "value": "h1n1"
        },
        {
          "value": "hancitor"
        },
        {
          "value": "hawkeye"
        },
        {
          "value": "icedid"
        },
        {
          "value": "iceid"
        },
        {
          "value": "iceix"
        },
        {
          "value": "isfb"
        },
        {
          "value": "jaff"
        },
        {
          "value": "kbot"
        },
        {
          "value": "kegotip"
        },
        {
          "value": "kins"
        },
        {
          "value": "kovter"
        },
        {
          "value": "kpot"
        },
        {
          "value": "kronos"
        },
        {
          "value": "locky"
        },
        {
          "value": "lokibot"
        },
        {
          "value": "madlocker"
        },
        {
          "value": "madness_pro"
        },
        {
          "value": "maoloa"
        },
        {
          "value": "mirai"
        },
        {
          "value": "mmbb"
        },
        {
          "value": "nanocore"
        },
        {
          "value": "necurs"
        },
        {
          "value": "netwire"
        },
        {
          "value": "neutrino"
        },
        {
          "value": "njrat"
        },
        {
          "value": "nymaim"
        },
        {
          "value": "odinaff"
        },
        {
          "value": "onliner"
        },
        {
          "value": "ostap"
        },
        {
          "value": "panda"
        },
        {
          "value": "phorpiex"
        },
        {
          "value": "pony"
        },
        {
          "value": "pushdo"
        },
        {
          "value": "qadars"
        },
        {
          "value": "qakbot"
        },
        {
          "value": "quantloader"
        },
        {
          "value": "quasarrat"
        },
        {
          "value": "ramnit"
        },
        {
          "value": "remcos"
        },
        {
          "value": "retefe"
        },
        {
          "value": "ruckguv"
        },
        {
          "value": "sage"
        },
        {
          "value": "sendsafe"
        },
        {
          "value": "shifu"
        },
        {
          "value": "slave"
        },
        {
          "value": "smokeloader"
        },
        {
          "value": "systembc"
        },
        {
          "value": "teslacrypt"
        },
        {
          "value": "test"
        },
        {
          "value": "testmod"
        },
        {
          "value": "tinba"
        },
        {
          "value": "tinba_dga"
        },
        {
          "value": "tinynuke"
        },
        {
          "value": "tofsee"
        },
        {
          "value": "torment"
        },
        {
          "value": "torrentlocker"
        },
        {
          "value": "trickbot"
        },
        {
          "value": "troldesh"
        },
        {
          "value": "unknown"
        },
        {
          "value": "vawtrak"
        },
        {
          "value": "vjworm"
        },
        {
          "value": "vmzeus"
        },
        {
          "value": "vmzeus2"
        },
        {
          "value": "wannacry"
        },
        {
          "value": "xagent"
        },
        {
          "value": "zeus"
        },
        {
          "value": "zloader"
        }
      ]
    }
  ]
}
